name: Deploy to AWS
on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: react-ecomm-app-prod
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          clean: true  # Ensure clean checkout

      - name: Clear npm cache
        run: |
          npm cache clean --force
          rm -rf node_modules
          rm -rf ~/.npm

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          cache: 'npm'  # Enable npm caching

      - name: Install dependencies
        run: npm ci

      - name: List files in pages directory
        run: ls -la src/pages/

      - name: Build application
        run: npm run build

      # ... rest of your existing deployment steps ...
